# config.py


NIFTY50 = [
"SI=F","RELIANCE","TCS","INFY","HDFCBANK","ICICIBANK","LT","ITC","HINDUNILVR",
"SBIN","BAJFINANCE","AXISBANK","KOTAKBANK","BHARTIARTL","HCLTECH",
"ASIANPAINT","SUNPHARMA","MARUTI","TITAN","ULTRACEMCO","WIPRO",
"NTPC","POWERGRID","BAJAJFINSV","NESTLEIND","JSWSTEEL",
"ADANIENT","ADANIPORTS","ONGC","COALINDIA","TECHM","INDUSINDBK",
"DIVISLAB","BRITANNIA","CIPLA","HDFCLIFE","SBILIFE","EICHERMOT",
"GRASIM","HINDALCO","HEROMOTOCO","DRREDDY","TATASTEEL","APOLLOHOSP",
"LTIM","SHRIRAMFIN","BPCL"
]

NIFTY200 = [
"RELIANCE.NS","TCS.NS","INFY.NS","HDFCBANK.NS","ICICIBANK.NS","LT.NS","ITC.NS","HINDUNILVR.NS",
"SBIN.NS","BAJFINANCE.NS","AXISBANK.NS","KOTAKBANK.NS","BHARTIARTL.NS","HCLTECH.NS",
"ASIANPAINT.NS","SUNPHARMA.NS","MARUTI.NS","TITAN.NS","ULTRACEMCO.NS","WIPRO.NS",
"NTPC.NS","POWERGRID.NS","BAJAJFINSV.NS","NESTLEIND.NS","JSWSTEEL.NS",
"ADANIENT.NS","ADANIPORTS.NS","ONGC.NS","COALINDIA.NS","TECHM.NS","INDUSINDBK.NS",
"DIVISLAB.NS","BRITANNIA.NS","CIPLA.NS","HDFCLIFE.NS","SBILIFE.NS","EICHERMOT.NS",
"GRASIM.NS","HINDALCO.NS","HEROMOTOCO.NS","DRREDDY.NS","TATASTEEL.NS","APOLLOHOSP.NS",
"LTIM.NS","SHRIRAMFIN.NS","BPCL.NS",

# Add midcaps
"ADANIPOWER.NS","PIDILITIND.NS","DMART.NS","GODREJCP.NS","AMBUJACEM.NS","BANKBARODA.NS",
"PNB.NS","CANBK.NS","CHOLAFIN.NS","TATAMOTORS.NS","M&M.NS","ICICIGI.NS","ICICIPRULI.NS",
"BAJAJ-AUTO.NS","SIEMENS.NS","ABB.NS","LUPIN.NS","GLAND.NS","BIOCON.NS","ALKEM.NS",
"AUBANK.NS","IDFCFIRSTB.NS","ZOMATO.NS","NYKAA.NS","PAYTM.NS","IRCTC.NS","HAL.NS"

]

# ===== KOTAK NEO CREDENTIALS =====
CONSUMER_KEY = "69546d09-a938-4535-a165-c9c72a825cdd"
CONSUMER_SECRET = ""
UCC = "Y6X1W"                 # Client ID
MPIN = "201031"
MOBILE_NUMBER = "+917032038240"  # Registered mobile
TOTP = "165839"               # 6-digit TOTP (generate dynamically later)

# ===== TRADING SETTINGS =====
EXCHANGE = "NSE"
INDEX_SYMBOL = "BANKNIFTY"
INDEX_TOKEN = 26009  # BANKNIFTY index (for data only)

BANKNIFTY_INDEX_TOKEN = "BANKNIFTY" 

# ===== RISK (we'll enforce later) =====
MAX_TRADES_PER_DAY = 3
MAX_LOSS_PER_DAY = 200  # INR

# Moving averages
SHORT_MA = 20        # 100 minutes
LONG_MA  = 100       # 500 minutes

# Donchian breakout
DONCHIAN_PERIOD = 55  # Turtle classic intraday

# RSI
RSI_PERIOD = 14
RSI_OVERSOLD = 20
RSI_OVERBOUGHT = 80

# Bollinger
BB_PERIOD = 20
BB_STD = 2.5

# Z-score
ZSCORE_PERIOD = 30
ZSCORE_ENTRY = 2.5

# ATR
ATR_PERIOD = 14
ATR_MULTIPLIER = 2.0

# Volatility regime
VOL_LOOKBACK = 100
MIN_HOLD_BARS = 10


# Volume filter
VOL_PERIOD = 20
VOL_MULTIPLIER = 0.1

# Regime detection
TREND_ADX_PERIOD = 14
TREND_THRESHOLD = 0.002  # ADX > 25 = trending

INITIAL_CAPITAL = 1000000
POSITION_SIZE = 1 * INITIAL_CAPITAL