STOCK_NAMES = {
    "RELIANCE": "Reliance Industries Limited",
    "TCS": "Tata Consultancy Services Limited",
    "INFY": "Infosys Limited",
    "HDFCBANK": "HDFC Bank Limited",
    "ICICIBANK": "ICICI Bank Limited",
    "LT": "Larsen & Toubro Limited",
    "ITC": "ITC Limited",
    "HINDUNILVR": "Hindustan Unilever Limited",
    "SBIN": "State Bank of India",
    "BAJFINANCE": "Bajaj Finance Limited",
    "AXISBANK": "Axis Bank Limited",
    "KOTAKBANK": "Kotak Mahindra Bank Limited",
    "BHARTIARTL": "Bharti Airtel Limited",
    "HCLTECH": "HCL Technologies Limited",
    "ASIANPAINT": "Asian Paints Limited",
    "SUNPHARMA": "Sun Pharmaceutical Industries Limited",
    "MARUTI": "Maruti Suzuki India Limited",
    "TITAN": "Titan Company Limited",
    "ULTRACEMCO": "UltraTech Cement Limited",
    "WIPRO": "Wipro Limited",
    "NTPC": "NTPC Limited",
    "POWERGRID": "Power Grid Corporation of India Limited",
    "BAJAJFINSV": "Bajaj Finserv Limited",
    "NESTLEIND": "Nestlé India Limited",
    "JSWSTEEL": "JSW Steel Limited",
    "ADANIENT": "Adani Enterprises Limited",
    "ADANIPORTS": "Adani Ports and Special Economic Zone Limited",
    "ONGC": "Oil and Natural Gas Corporation Limited",
    "COALINDIA": "Coal India Limited",
    "TECHM": "Tech Mahindra Limited",
    "INDUSINDBK": "IndusInd Bank Limited",
    "DIVISLAB": "Divi’s Laboratories Limited",
    "BRITANNIA": "Britannia Industries Limited",
    "CIPLA": "Cipla Limited",
    "HDFCLIFE": "HDFC Life Insurance Company Limited",
    "SBILIFE": "SBI Life Insurance Company Limited",
    "EICHERMOT": "Eicher Motors Limited",
    "GRASIM": "Grasim Industries Limited",
    "HINDALCO": "Hindalco Industries Limited",
    "HEROMOTOCO": "Hero MotoCorp Limited",
    "DRREDDY": "Dr. Reddy’s Laboratories Limited",
    "TATASTEEL": "Tata Steel Limited",
    "APOLLOHOSP": "Apollo Hospitals Enterprise Limited",
    "LTIM": "LTIMindtree Limited",
    "SHRIRAMFIN": "Shriram Finance Limited",
    "BPCL": "Bharat Petroleum Corporation Limited"
}
