# config.py

# ===== KOTAK NEO CREDENTIALS =====
CONSUMER_KEY = "69546d09-a938-4535-a165-c9c72a825cdd"
CONSUMER_SECRET = ""
UCC = "Y6X1W"                 # Client ID
MPIN = "201031"
MOBILE_NUMBER = "+917032038240"  # Registered mobile
TOTP = "106950"               # 6-digit TOTP (generate dynamically later)

# ===== TRADING SETTINGS =====
EXCHANGE = "NSE"
INDEX_SYMBOL = "BANKNIFTY"
INDEX_TOKEN = 26009  # BANKNIFTY index (for data only)

BANKNIFTY_INDEX_TOKEN = "BANKNIFTY" 

INITIAL_CAPITAL = 1000000
POSITION_SIZE = 1 * INITIAL_CAPITAL


NIFTY200 = [
"RELIANCE","TCS","INFY","HDFCBANK","ICICIBANK","LT","ITC","HINDUNILVR",
"SBIN","BAJFINANCE","AXISBANK","KOTAKBANK","BHARTIARTL","HCLTECH",
"ASIANPAINT","SUNPHARMA","MARUTI","TITAN","ULTRACEMCO","WIPRO",
"NTPC","POWERGRID","BAJAJFINSV","NESTLEIND","JSWSTEEL","ADANIENT",
"ADANIPORTS","ONGC","COALINDIA","TECHM","INDUSINDBK","DIVISLAB",
"BRITANNIA","CIPLA","HDFCLIFE","SBILIFE","EICHERMOT","GRASIM",
"HINDALCO","HEROMOTOCO","DRREDDY","TATASTEEL","APOLLOHOSP","LTIM",
"SHRIRAMFIN","BPCL","PIDILITIND","DMART","GODREJCP","AMBUJACEM",
"PNB","BANKBARODA","CANBK","CHOLAFIN","TATAMOTORS","M&M","AUBANK",
"ICICIGI","ICICIPRULI","BAJAJ-AUTO","SIEMENS","ABB","LUPIN",
"BIOCON","ALKEM","IRCTC","HAL","ZOMATO","NYKAA","PAYTM"
]
